
services:
  spring-server:
    build: .
    container_name: spring-server
    ports:
      - "8080:8080"
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy
    environment:
      - SPRING_DATA_REDIS_HOST=my-cache-server
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_SSL_ENABLED=false
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
    restart: on-failure

  fastapi-server:
    build: ../ai-backend
    container_name: fastapi-server
    ports:
      - "8000:8000"
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy


  my-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clothes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 5s

  my-cache-server:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
  nginx:
    image: nginx:1.24.0
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../server-frontend/dist:/usr/share/nginx/html:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - spring-server
    restart: always


volumes:
  pgdata:
