version: '3.8'

services:
  postgres:
    image: postgres:16.9-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: clothes
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    image: demo-server
    container_name: spring-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clothes
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  pgdata: