CREATE TABLE IF NOT EXISTS weather (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    weather_prompt TEXT,
    image TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    user_code VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    user_name VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS boards(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(100),
    content TEXT,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS comment (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    board_id BIGINT,
    weather_id BIGINT,
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);